In [1]:
import pandas as pd

In [2]:
data_2009 = pd.read_csv('2009.csv')

In [3]:
data_2009

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,62.0,68.0,42.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,82.0,75.0,43.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,70.0,62.0,36.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,77.0,56.0,37.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,105.0,77.0,40.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6429333,2009-12-31,YV,2846,YUM,PHX,615,605.0,-10.0,19.0,624.0,...,67.0,71.0,39.0,160.0,NaN,NaN,NaN,NaN,NaN,NaN
6429334,2009-12-31,YV,2850,YUM,PHX,1929,1919.0,-10.0,7.0,1926.0,...,70.0,61.0,48.0,160.0,NaN,NaN,NaN,NaN,NaN,NaN
6429335,2009-12-31,YV,2866,YUM,PHX,1400,1400.0,0.0,29.0,1429.0,...,55.0,70.0,32.0,160.0,0.0,0.0,15.0,0.0,0.0,NaN
6429336,2009-12-31,YV,2868,YUM,PHX,1620,1615.0,-5.0,10.0,1625.0,...,67.0,61.0,45.0,160.0,NaN,NaN,NaN,NaN,NaN,NaN
6429337,2009-12-31,YV,2871,YUM,PHX,1123,1113.0,-10.0,14.0,1127.0,...,67.0,64.0,35.0,160.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data_2010 = pd.read_csv('2010.csv')

In [5]:
data_2010

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2010-01-01,MQ,4438,LGA,RDU,1940,2101.0,81.0,14.0,2115.0,...,110.0,106.0,70.0,431.0,0.0,0.0,0.0,0.0,77.0,NaN
1,2010-01-01,MQ,4440,DCA,JFK,950,949.0,-1.0,13.0,1002.0,...,70.0,60.0,38.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-01,MQ,4443,LGA,RDU,900,937.0,37.0,11.0,948.0,...,120.0,91.0,77.0,431.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-01,MQ,4445,RDU,LGA,1940,1935.0,-5.0,12.0,1947.0,...,100.0,80.0,64.0,431.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-01,MQ,4447,JFK,DCA,2035,2236.0,121.0,18.0,2254.0,...,85.0,66.0,47.0,213.0,0.0,0.0,0.0,0.0,102.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6450112,2010-12-31,US,2175,LGA,DCA,1300,1252.0,-8.0,8.0,1300.0,...,67.0,52.0,41.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6450113,2010-12-31,US,2176,DCA,LGA,1500,1457.0,-3.0,15.0,1512.0,...,81.0,61.0,41.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6450114,2010-12-31,US,2183,LGA,DCA,1700,1652.0,-8.0,10.0,1702.0,...,76.0,59.0,44.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6450115,2010-12-31,US,2184,DCA,LGA,1900,1859.0,-1.0,8.0,1907.0,...,85.0,54.0,40.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6450116,2010-12-31,US,2191,LGA,DCA,2100,2046.0,-14.0,10.0,2056.0,...,74.0,53.0,40.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_2011 = pd.read_csv('2011.csv')
data_2011

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2011-01-01,MQ,4529,BOS,JFK,1830,1823.0,-7.0,68.0,1931.0,...,90.0,146.0,48.0,187.0,0.0,0.0,49.0,0.0,0.0,NaN
1,2011-01-01,MQ,4532,BNA,DCA,1100,1052.0,-8.0,11.0,1103.0,...,95.0,88.0,74.0,562.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-01-01,MQ,4532,DCA,JFK,1400,1358.0,-2.0,9.0,1407.0,...,79.0,73.0,60.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-01-01,MQ,4537,RDU,JFK,1710,1706.0,-4.0,59.0,1805.0,...,105.0,159.0,85.0,426.0,0.0,0.0,50.0,0.0,0.0,NaN
4,2011-01-01,MQ,4540,CMH,LGA,1340,1340.0,0.0,14.0,1354.0,...,105.0,95.0,77.0,478.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6066645,2011-12-31,US,2138,LGA,BOS,1800,1748.0,-12.0,13.0,1801.0,...,75.0,50.0,33.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN
6066646,2011-12-31,US,2168,DCA,LGA,1100,1055.0,-5.0,10.0,1105.0,...,71.0,59.0,41.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6066647,2011-12-31,US,2175,LGA,DCA,1300,1257.0,-3.0,18.0,1315.0,...,68.0,65.0,45.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6066648,2011-12-31,US,2176,DCA,LGA,1500,1455.0,-5.0,11.0,1506.0,...,81.0,57.0,41.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN
6066649,2011-12-31,US,2183,LGA,DCA,1700,1651.0,-9.0,14.0,1705.0,...,77.0,60.0,43.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data_2012 = pd.read_csv('2012.csv')
data_2012

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2012-01-01,MQ,4041,BMI,ORD,1715.0,1702.0,-13.0,9.0,1711.0,...,55.0,55.0,37.0,116.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-01-01,MQ,4041,ORD,BMI,1545.0,1540.0,-5.0,11.0,1551.0,...,50.0,39.0,23.0,116.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-01,MQ,4042,SGF,ORD,715.0,705.0,-10.0,12.0,717.0,...,115.0,105.0,75.0,438.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-01,MQ,4045,ORD,DBQ,1535.0,1529.0,-6.0,13.0,1542.0,...,55.0,46.0,31.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-01,MQ,4047,ORD,RIC,1600.0,1615.0,15.0,12.0,1627.0,...,115.0,109.0,86.0,642.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6096757,2012-12-31,YV,1036,HNL,KOA,1600.0,1610.0,10.0,14.0,1624.0,...,40.0,50.0,32.0,163.0,0.0,0.0,10.0,0.0,10.0,NaN
6096758,2012-12-31,YV,1054,HNL,KOA,1252.0,1250.0,-2.0,15.0,1305.0,...,40.0,52.0,32.0,163.0,NaN,NaN,NaN,NaN,NaN,NaN
6096759,2012-12-31,YV,1004,HNL,LIH,1300.0,1321.0,21.0,17.0,1338.0,...,37.0,45.0,21.0,102.0,0.0,0.0,8.0,0.0,21.0,NaN
6096760,2012-12-31,YV,1005,HNL,LIH,1500.0,1500.0,0.0,12.0,1512.0,...,37.0,41.0,25.0,102.0,NaN,NaN,NaN,NaN,NaN,NaN
6096761,2012-12-31,YV,1017,HNL,LIH,1700.0,1700.0,0.0,5.0,1705.0,...,37.0,31.0,23.0,102.0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data_2013 = pd.read_csv('2013.csv')
data_2013

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2013-01-01,VX,108,LAX,IAD,700,700.0,0.0,8.0,708.0,...,285.0,258.0,243.0,2288.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-01-01,VX,114,LAX,IAD,2205,2204.0,-1.0,12.0,2216.0,...,280.0,272.0,247.0,2288.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-01-01,VX,11,JFK,SFO,730,729.0,-1.0,18.0,747.0,...,405.0,380.0,356.0,2586.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-01-01,VX,121,PHL,LAX,700,700.0,0.0,14.0,714.0,...,360.0,374.0,352.0,2402.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-01-01,VX,124,LAX,PHL,1100,1104.0,4.0,12.0,1116.0,...,315.0,273.0,252.0,2402.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6369477,2013-12-31,MQ,3271,IND,ORD,1100,1054.0,-6.0,14.0,1108.0,...,65.0,73.0,43.0,177.0,NaN,NaN,NaN,NaN,NaN,NaN
6369478,2013-12-31,MQ,3271,ORD,IND,830,829.0,-1.0,11.0,840.0,...,55.0,47.0,32.0,177.0,NaN,NaN,NaN,NaN,NaN,NaN
6369479,2013-12-31,MQ,3272,CLE,LGA,1050,1155.0,65.0,25.0,1220.0,...,95.0,91.0,63.0,419.0,61.0,0.0,0.0,0.0,0.0,NaN
6369480,2013-12-31,MQ,3272,LGA,CLE,825,815.0,-10.0,16.0,831.0,...,100.0,101.0,79.0,419.0,NaN,NaN,NaN,NaN,NaN,NaN
6369481,2013-12-31,MQ,3273,CMI,ORD,905,901.0,-4.0,24.0,925.0,...,60.0,66.0,33.0,135.0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data_2014 = pd.read_csv('2014.csv')
data_2014

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2014-01-01,AA,2377,ICT,DFW,1135,1144.0,9.0,12.0,1156.0,...,85.0,78.0,57.0,328.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-01,AA,2378,MIA,TPA,2225,2220.0,-5.0,14.0,2234.0,...,60.0,55.0,37.0,204.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-01,EV,2500,DFW,HOU,2105,NaN,NaN,NaN,NaN,...,60.0,NaN,NaN,247.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-01-01,EV,2502,CRW,DFW,1655,1805.0,70.0,6.0,1811.0,...,185.0,180.0,150.0,946.0,0.0,0.0,0.0,0.0,65.0,NaN
4,2014-01-01,EV,2502,DFW,CRW,1320,1440.0,80.0,9.0,1449.0,...,125.0,115.0,101.0,946.0,6.0,0.0,0.0,0.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819806,2014-12-31,MQ,3552,RDU,LGA,640,635.0,-5.0,37.0,712.0,...,100.0,101.0,59.0,431.0,NaN,NaN,NaN,NaN,NaN,NaN
5819807,2014-12-31,MQ,3555,CMH,ORD,720,752.0,32.0,11.0,803.0,...,90.0,110.0,58.0,296.0,32.0,0.0,20.0,0.0,0.0,NaN
5819808,2014-12-31,MQ,3564,GSO,LGA,1010,1007.0,-3.0,8.0,1015.0,...,95.0,76.0,64.0,461.0,NaN,NaN,NaN,NaN,NaN,NaN
5819809,2014-12-31,MQ,3611,CAE,DFW,600,556.0,-4.0,17.0,613.0,...,185.0,188.0,164.0,922.0,NaN,NaN,NaN,NaN,NaN,NaN
5819810,2014-12-31,MQ,3612,CLL,DFW,1120,1125.0,5.0,7.0,1132.0,...,55.0,51.0,37.0,164.0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data_2015 = pd.read_csv('2015.csv')
data_2015

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2015-01-01,NK,195,MCO,FLL,2147,2143.0,-4.0,15.0,2158.0,...,63.0,62.0,40.0,177.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01,NK,197,LGA,FLL,1050,1104.0,14.0,20.0,1124.0,...,194.0,179.0,150.0,1076.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-01,NK,198,FLL,MCO,700,712.0,12.0,19.0,731.0,...,57.0,61.0,32.0,177.0,0.0,0.0,16.0,0.0,0.0,NaN
3,2015-01-01,NK,199,IAH,LAS,2240,2251.0,11.0,8.0,2259.0,...,196.0,176.0,164.0,1222.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-01,NK,200,IAH,ORD,623,620.0,-3.0,15.0,635.0,...,152.0,140.0,115.0,925.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015-12-31,MQ,3058,ORD,ABQ,1015,1015.0,0.0,23.0,1038.0,...,187.0,197.0,170.0,1118.0,NaN,NaN,NaN,NaN,NaN,NaN
5819075,2015-12-31,MQ,3059,DFW,LCH,1210,1338.0,88.0,12.0,1350.0,...,78.0,68.0,53.0,295.0,68.0,0.0,0.0,0.0,10.0,NaN
5819076,2015-12-31,MQ,3059,LCH,DFW,1358,1510.0,72.0,12.0,1522.0,...,82.0,79.0,53.0,295.0,0.0,0.0,0.0,0.0,69.0,NaN
5819077,2015-12-31,MQ,3060,DFW,FAR,1830,1840.0,10.0,12.0,1852.0,...,163.0,NaN,NaN,968.0,NaN,NaN,NaN,NaN,NaN,NaN
5819078,2015-12-31,MQ,3061,LCH,DFW,630,757.0,87.0,12.0,809.0,...,82.0,77.0,52.0,295.0,82.0,0.0,0.0,0.0,0.0,NaN

In [11]:
data_2016 = pd.read_csv('2016.csv')
data_2016

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2016-01-01,DL,1248,DTW,LAX,1935,1935.0,0.0,23.0,1958.0,...,309.0,285.0,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,DL,1251,ATL,GRR,2125,2130.0,5.0,13.0,2143.0,...,116.0,109.0,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,DL,1254,LAX,ATL,2255,2256.0,1.0,19.0,2315.0,...,245.0,231.0,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,DL,1255,SLC,ATL,1656,1700.0,4.0,12.0,1712.0,...,213.0,193.0,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,DL,1256,BZN,MSP,900,1012.0,72.0,63.0,1115.0,...,136.0,188.0,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5617653,2016-12-31,NK,112,IAH,BWI,615,613.0,-2.0,12.0,625.0,...,170.0,167.0,144.0,1235.0,NaN,NaN,NaN,NaN,NaN,NaN
5617654,2016-12-31,NK,113,BWI,IAH,2108,2229.0,81.0,9.0,2238.0,...,214.0,200.0,182.0,1235.0,0.0,0.0,0.0,0.0,67.0,NaN
5617655,2016-12-31,NK,121,ORD,RSW,700,704.0,4.0,11.0,715.0,...,172.0,151.0,136.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5617656,2016-12-31,NK,124,RSW,ORD,1704,1711.0,7.0,9.0,1720.0,...,183.0,170.0,154.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5617657,2016-12-31,NK,126,FLL,MYR,2015,2208.0,113.0,21.0,2229.0,...,98.0,102.0,75.0,529.0,113.0,0.0,4.0,0.0,0.0,NaN

In [12]:
data_2017 = pd.read_csv('2017.csv')
data_2017

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2017-01-01,AA,1,JFK,LAX,800,831.0,31.0,25.0,856.0,...,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0,NaN
1,2017-01-01,AA,2,LAX,JFK,900,934.0,34.0,34.0,1008.0,...,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0,NaN
2,2017-01-01,AA,4,LAX,JFK,1130,1221.0,51.0,20.0,1241.0,...,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0,NaN
3,2017-01-01,AA,5,DFW,HNL,1135,1252.0,77.0,19.0,1311.0,...,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0,NaN
4,2017-01-01,AA,6,OGG,DFW,1855,1855.0,0.0,16.0,1911.0,...,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5674616,2017-12-31,UA,2421,IAH,LAS,750,744.0,-6.0,14.0,758.0,...,206.0,189.0,171.0,1222.0,NaN,NaN,NaN,NaN,NaN,NaN
5674617,2017-12-31,UA,2425,RSW,ORD,1611,1602.0,-9.0,12.0,1614.0,...,190.0,183.0,159.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
5674618,2017-12-31,UA,2426,SNA,DEN,1335,1334.0,-1.0,9.0,1343.0,...,134.0,123.0,104.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN
5674619,2017-12-31,UA,2427,LAS,SFO,1115,1107.0,-8.0,11.0,1118.0,...,99.0,92.0,66.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN
5674620,2017-12-31,UA,2429,EWR,DEN,1510,1612.0,62.0,28.0,1640.0,...,270.0,266.0,227.0,1605.0,58.0,0.0,0.0,0.0,0.0,NaN

In [13]:
data_2018 = pd.read_csv('2018.csv')
data_2018

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2018-01-01,UA,2429,EWR,DEN,1517,1512.0,-5.0,15.0,1527.0,...,268.0,250.0,225.0,1605.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01,UA,2427,LAS,SFO,1115,1107.0,-8.0,11.0,1118.0,...,99.0,83.0,65.0,414.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01,UA,2426,SNA,DEN,1335,1330.0,-5.0,15.0,1345.0,...,134.0,126.0,106.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,UA,2425,RSW,ORD,1546,1552.0,6.0,19.0,1611.0,...,190.0,182.0,157.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01,UA,2424,ORD,ALB,630,650.0,20.0,13.0,703.0,...,112.0,106.0,83.0,723.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213441,2018-12-31,AA,1815,DCA,CLT,1534,1530.0,-4.0,20.0,1550.0,...,100.0,99.0,72.0,331.0,NaN,NaN,NaN,NaN,NaN,NaN
7213442,2018-12-31,AA,1816,CLT,DFW,1751,1757.0,6.0,18.0,1815.0,...,181.0,176.0,148.0,936.0,NaN,NaN,NaN,NaN,NaN,NaN
7213443,2018-12-31,AA,1817,CLT,MEM,2015,2010.0,-5.0,36.0,2046.0,...,112.0,128.0,88.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN
7213444,2018-12-31,AA,1818,CLT,RDU,1300,1323.0,23.0,11.0,1334.0,...,50.0,41.0,26.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN
7213445,2018-12-31,AA,1818,RDU,CLT,1435,1443.0,8.0,8.0,1451.0,...,71.0,59.0,44.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
data = pd.concat([data_2009, data_2010, data_2011,data_2012,data_2013,data_2014,data_2015,data_2016,data_2017,data_2018])

In [15]:
data

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2009-01-01,XE,1204,DCA,EWR,1100.0,1058.0,-2.0,18.0,1116.0,...,62.0,68.0,42.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510.0,1509.0,-1.0,28.0,1537.0,...,82.0,75.0,43.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100.0,1059.0,-1.0,20.0,1119.0,...,70.0,62.0,36.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240.0,1249.0,9.0,10.0,1259.0,...,77.0,56.0,37.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715.0,1705.0,-10.0,24.0,1729.0,...,105.0,77.0,40.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213441,2018-12-31,AA,1815,DCA,CLT,1534.0,1530.0,-4.0,20.0,1550.0,...,100.0,99.0,72.0,331.0,NaN,NaN,NaN,NaN,NaN,NaN
7213442,2018-12-31,AA,1816,CLT,DFW,1751.0,1757.0,6.0,18.0,1815.0,...,181.0,176.0,148.0,936.0,NaN,NaN,NaN,NaN,NaN,NaN
7213443,2018-12-31,AA,1817,CLT,MEM,2015.0,2010.0,-5.0,36.0,2046.0,...,112.0,128.0,88.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN
7213444,2018-12-31,AA,1818,CLT,RDU,1300.0,1323.0,23.0,11.0,1334.0,...,50.0,41.0,26.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN
7213445,2018-12-31,AA,1818,RDU,CLT,1435.0,1443.0,8.0,8.0,1451.0,...,71.0,59.0,44.0,130.0,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data.isnull().sum()

FL_DATE                       0
OP_CARRIER                    0
OP_CARRIER_FL_NUM             0
ORIGIN                        0
DEST                          0
CRS_DEP_TIME                  1
DEP_TIME                 935723
DEP_DELAY                940675
TAXI_OUT                 963901
WHEELS_OFF               963896
WHEELS_ON                997016
TAXI_IN                  997015
CRS_ARR_TIME                  2
ARR_TIME                 997015
ARR_DELAY               1121351
CANCELLED                     0
CANCELLATION_CODE      60583755
DIVERTED                      0
CRS_ELAPSED_TIME             60
ACTUAL_ELAPSED_TIME     1118754
AIR_TIME                1118753
DISTANCE                      0
CARRIER_DELAY          50166224
WEATHER_DELAY          50166224
NAS_DELAY              50166224
SECURITY_DELAY         50166224
LATE_AIRCRAFT_DELAY    50166224
Unnamed: 27            61556964
dtype: int64

In [17]:
data.to_csv('data.csv',index=False)

In [1]:
61556964-11390402

50166562